apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - guestbook-deploy.yaml
  - guestbook-svc.yaml
  - guestbook-ns.yaml

patches:
  - target:
      kind: Namespace
    path: istio-injection-patch.yaml
